### ISSUE TITLE
Issue with @RequestScope after top-level suspension of kotlin coroutine 

### ISSUE THREAD

**Issue by timducheyne** [micronaut-projects/micronaut-kotlin#226]
### Steps to Reproduce

```kotlin
@RequestScope
class RequestContextService {
    val id: String = UUID.randomUUID().toString()
}

@Controller
class HelloController(
    private val requestContextService: RequestContextService
) {
    @Get("/hello")
    suspend fun hello() {
        println("test ${requestContextService.id}")
        delay(100)
        println("test ${requestContextService.id}")
    }
}
```

just call /hello
the first call to requestContextService.id will give the correct scoped value
but after the delay (supends the coroutine), the second call will fail with a no such bean exception

Note: that it does work when suspension in async blocks or when running on a dispatcher 

### Expected Behaviour

The request scope should be maintained

### Actual Behaviour
```
17:45:16.741 [kotlinx.coroutines.DefaultExecutor] ERROR i.m.h.s.netty.RoutingInBoundHandler - Unexpected error occurred: No bean of type [io.micronaut.docs.server.suspend.SuspendRequestScopedService] exists for the given qualifier: @RequestScope. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [io.micronaut.docs.server.suspend.SuspendRequestScopedService] exists for the given qualifier: @RequestScope. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
	at io.micronaut.runtime.http.scope.RequestCustomScope.get(RequestCustomScope.java:82)
	at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2399)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2339)
	at io.micronaut.context.DefaultBeanContext.getProxyTargetBean(DefaultBeanContext.java:1070)
	at io.micronaut.docs.server.suspend.$SuspendRequestScopedServiceDefinition$Intercepted.$resolveTarget(Unknown Source)
	at io.micronaut.docs.server.suspend.$SuspendRequestScopedServiceDefinition$Intercepted.interceptedTarget(Unknown Source)
	at io.micronaut.docs.server.suspend.$SuspendRequestScopedServiceDefinition$Intercepted.getRequestId(Unknown Source)
	at io.micronaut.docs.server.suspend.SuspendController.keepRequestScopeAfterSuspend(SuspendController.kt:135)
	at io.micronaut.docs.server.suspend.SuspendController$keepRequestScopeAfterSuspend$1.invokeSuspend(SuspendController.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:362)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:396)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:388)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:484)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:489)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Environment Information

- **Micronaut Version:** 2.3.x
- **JDK Version:** 11

**Comment by timducheyne** [comment]
Created PR with fix for this:
https://github.com/micronaut-projects/micronaut-core/pull/4904

**Comment by graemerocher** [comment]
Thanks for the contribution!
